### ISSUE TITLE
Container dies unable to query logs

### ISSUE THREAD

**Issue by Nosferican** [jamesnetherton/docker-atom-editor#99]
Greetings,

I have a docker-compose.yml as following
```
version: "3.7"
services:
  # Atom
  atom:
    image: jamesnetherton/docker-atom-editor:v1.43.0
    container_name: atom
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
```
When trying to spin the container,
```
docker-compose -f docker-compose.yml up -d atom
```
The container exists, but trying to check the logs doesn't help.
```
> docker logs atom
(atom:17): Gtk-WARNING **: 18:06:56.355: cannot open display: 
```
